name = "chemvault-user"
compatibility_date = "2026-06-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "chemvault_user"
database_id = "52eb0a6f-2905-4bd2-a58c-e95c262bb47f"

[[r2_buckets]]
binding = "AVATARS"
bucket_name = "chemvault-user-avatars"

[vars]
COOKIE_NAME = "chemvault_session"
NODE_ENV = "production"

# Configure secrets outside this file:
# wrangler pages secret put JWT_SECRET --project-name chemvault-user
# wrangler pages secret put MAIL_SYSTEM_SYNC_SECRET --project-name chemvault-user
